name: push to branch
on:
  push:
    branches: ["*"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install pnpm
        uses: npm install -g pnpm
      - uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: "pnpm"
      - name: Install the dependencies
        run: pnpm install
      - name: Run tests
        run: pnpm test
